language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: nosetests indor -v --with-coverage --cover-test --cover-package=indor --cover-min-percentage=75
deploy:
  provider: pypi
  user: godlark
  password:
    secure: UwY+WNipdmqFnLTY8RCJi8elvhIEqkrKO8yf1di8Tv1GtxPE5UUOw4NAH2PXW2sFLIVz5Rdgka12xQHieD4qwjL1YWnzODcIYIKlRZkWz/BuS4wQ78SNZNDGY/+3+IxcDjIG4YhORfdBCnqCKEd1aX9JbRKjXlam0M49X2YGugo=
  on:
    tags: true
    repo: nokia-wroclaw/innovativeproject-resttest
    all_branches: true
notifications:
  email:
  - slawomir.karol.domagala@gmail.com
