language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: ./scripts/test.sh
deploy:
  provider: pypi
  user: DeeM
  password:
    secure: oEX2JJIgWuARdnfZMzn4ADI+zoWEZNzlal286n88PoXGd9udsIXX0Ojh6mdoZn9xxIcknWZ8mRhch59s3MctjQo0IacsthjwFrPduplxwR7iO+uf21K+Uqv5YSMELzgHtVe3SgB5e6D2EPfr/oF9nJyc2be6oxIQICVfLKAaU+Q=
  on:
    tags: true
    repo: nokia-wroclaw/innovativeproject-resttest
    all_branches: python3
notifications:
  email:
    - slawomir.karol.domagala@gmail.com